### ISSUE TITLE
Publish v1.1.0 version

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/elixir-auth-microsoft#10]
Creating this so @nelsonic doesn't forget and can refer to this whenever he can. 

Long story short, I've tagged the new version, could you publish it? It seems that I can't do it, my account is unauthorized 🤷 .

<img width="422" alt="Screenshot 2022-10-26 at 16 14 30" src="https://user-images.githubusercontent.com/17494745/198065710-d0fab785-e47c-4a79-9b4c-dba58a36bc93.png">

**Comment by nelsonic** [comment]
Picking this up *Now* so that you can publish the new version so @tmjoen can ***`use`*** it. 👌

**Comment by nelsonic** [comment]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/194400/198247892-7e1d2999-eda7-41ba-9bf6-11ad1088cb9e.png">

@LuchoTurtle you should be able to `mix hex.publish` on the `main` branch 🤞 📦 :shipit:

**Comment by LuchoTurtle** [comment]
It's published now -> https://hex.pm/packages/elixir_auth_microsoft

**Comment by nelsonic** [comment]
https://diff.hex.pm/diff/elixir_auth_microsoft/1.0.0..1.1.0 ✅
