### ISSUE TITLE
Feat: Checking for env variables

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/elixir-auth-microsoft#3]
Writing this issue so I don't forget some crucial aspects to get this package up and running.
In the same fashion as [`auth-google`](https://github.com/dwyl/elixir-auth-google) raises an error when no env variables are set, we need the same mechanism so the package doesn't go kaboom 💥

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for opening this to capture the work that needs to be done. 👌 
Definitely borrow as much code from the Google Auth implementation as you can. ♻️ 
If you have _any_ questions please comment/ask! 🙏
