### ISSUE TITLE
feature/support taking callback_uri from custom configuration

### ISSUE THREAD

**Issue by robdembitel** [dwyl/elixir-auth-microsoft#39]
Hello, would it be possible to also make it possible to set the callback path via the configuration file?

https://github.com/dwyl/elixir-auth-microsoft/blob/1637cb4afeac20ecd8c09b968b19ab80cc64f708/lib/elixir_auth_microsoft.ex#L164

I would suggest to align it with the other environment variables, like here:
https://github.com/dwyl/elixir-auth-microsoft/blob/1637cb4afeac20ecd8c09b968b19ab80cc64f708/lib/elixir_auth_microsoft.ex#L156

so that set it also via the config file like e.g. this:

```
config :elixir_auth_microsoft,
  client_id: "",
  client_secret: "",
  post_logout_redirect_uri: "http://localhost:4000/auth/microsoft/logout",
  callback_uri: "http://localhost:4000/auth/microsoft/custom-callback-uri",
```

So this would be cool:

```
  defp get_callback_path do
    System.get_env("MICROSOFT_CALLBACK_PATH") || Application.get_env(:elixir_auth_microsoft, :callback_uri) || @default_callback_path
  end
```

Cheers!

**Comment by LuchoTurtle** [comment]
Feature added and it's part of the `v1.3.0` release of the package, which is already published. https://hex.pm/packages/elixir_auth_microsoft

Thanks!
