### ISSUE TITLE
error resolving dependencies

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-microsoft#45]
When trying to use this library, @cheerfulstoic was getting an error in resolving dependencies:

```
Resolving Hex dependencies...
Resolution completed in 0.232s
Because "the lock" specifies httpoison 2.2.0 and elixir_auth_microsoft >= 1.1.1 depends on httpoison ~> 2.1.0, the lock is incompatible with elixir_auth_microsoft >= 1.1.1.
And because elixir_auth_microsoft < 1.1.1 depends on httpoison ~> 1.8.0, if the lock and elixir_auth_microsoft then httpoison ~> 1.8.0.
And because your app depends on the lock, elixir_auth_microsoft requires httpoison ~> 1.8.0.
And because your app depends on elixir_auth_microsoft ~> 1.1.0, httpoison ~> 1.8.0 is required.
So, because your app depends on httpoison ~> 2.0, version solving failed.
```

_Originally posted by @cheerfulstoic in https://github.com/dwyl/elixir-auth-microsoft/issues/42#issuecomment-1916548595_
            

We need to freeze the dependency on `httpoison` and `jason` to the lowest _secure/stable_ version to maximise downstream compatibility.

**Comment by nelsonic** [comment]
PR: #46 :shipit: 
CC: @cheerfulstoic

**Comment by nelsonic** [comment]
Ah …. 💭
If you have a minute to translate this to a PR. 🧑‍💻
We’d be very grateful. 🙏

**Comment by LuchoTurtle** [comment]
Feature added and it's part of the `v1.3.0` release of the package, which is already published. https://hex.pm/packages/elixir_auth_microsoft

Thanks!
