### ISSUE TITLE
What's the correct way to enforce that users are logged in when visiting an URL?

### ISSUE THREAD

**Issue by stabenfeldt** [dwyl/elixir-auth-microsoft#54]
Hi,

The gen.auth project has a `require_authenticated_user()` plug that can be used.
I could not find anything here.

Can you guys please guide me on how the best security practices for implementing something similar?

**Comment by ndrean** [comment]
Adding my one cent. For `Liveview,` one can rewritte this by using [on_mount](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#on_mount/1) to "_slightly clean_" the code.

It can be used as the callback module of the `live_session` macro in the router, or declared directly (as a macro) in the Live component:.
Check this [post](https://dev.to/herminiotorres/how-to-take-leverage-from-onmount-to-reduce-code-2027)

**Comment by stabenfeldt** [comment]
Thanks for the good and detailed answers, @LuchoTurtle & @ndrean! ❤️
You gave me a good starting point.
